### ISSUE TITLE
Delegate methods don't pass the KBKeyboardObserver object. 

### ISSUE THREAD

**Issue by erichocean** [kam800/KBKeyboardObserver#1]
It's standard to do so, so that a single delegate object can work with multiple keyboardObserver objects. (You'll notice that all of Apple's delegate APIs work that way, too.)

**Comment by kam800** [comment]
Hey. Thanks for your advice.
You are right, that this delegate is not consistent with Apple API.
I thought about passing KBKeyboardObserver in delegate method. I realized that every KBKeyboardObserver instance listens for app-global keyboard notifications, so I thought there is no sense to register few observers with the same delegate. I also wanted to keep delegate as simple as it can be - for user convenience.
What do you think about my argumentation? I would be pleased to hear from you :)

**Comment by erichocean** [comment]
Well, right now they're associated with a specific view, which the delegate could use to respond differently for. I do get your point though, and what I ended up doing in the end was registering for them globally and dispatching to whatever part of my app was active at the time.

What's nice about your code is just tightening up the keyboard API to what you actually need from it—rects in a specific view's frame coordinate system—so that you can react to them. I ended up just copying that code specifically and making that globally available (pass in a view and the keyboard notification, get back the rect).

**Comment by kam800** [comment]
Oh, you are absolutely right! My mistake. I will fix this code :)

**Comment by kam800** [comment]
Thanks for your suggestions :) Issue has been solved and new version 0.0.2 has been released to cocoapods.
